# Generated by Django 4.2.1 on 2023-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='complement_adresse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
